
MCU_FAMILY = MIMXRT1062
MCU_SERIES = MIMXRT1062
MCU_LDSCRIPT = MIMXRT1062
MCU_STARTUP = MIMXRT1062
ARMV = 7

# https://github.com/kinx-project/kint/issues/77
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=FALSE
